### ISSUE TITLE
Replace `BatchKey` with epochs

### ISSUE THREAD

**Issue by parketh** [parketh/babylon-eots-verifier#1]
## Summary

Remove `BatchKey` and arrange pub rand commitments as epochs to enforce regular batch windows.

## Description

We currently use `BatchKey` to track / id each pub rand batch.

```
struct BatchKey {
  /// @notice Chain ID
  uint32 chainId;
  /// @notice Block number at which batch starts
  uint64 fromBlock;
  /// @notice Block number at which batch ends
  uint64 toBlock;
}
```

However, as per discussion with @bap2pecs:
1. each FP can only protect one consumer chain
2. it would be cleaner to have a single EOTS verifier contract per L2 consumer and set the chain ID at deployment
3. rather than allow FPs to specify `fromBlock` and `toBlock`, we should arrange commitments as epochs to enforce regular batch windows for every FP. The starting L2 block and epoch size will be defined at contract deployment, and batches identified with a single epoch id.

This means the `BatchKey` struct can be removed.

## Proposed changes

- [ ] Set chain ID, starting L2 block, and epoch size at contract deployment
- [ ] Remove `BatchKey` and replace it with `uint64 epoch`
- [ ] Refactor storage to enforce regular batch windows (epochs) and single chain ID

**Comment by bap2pecs** [comment]
@parketh shall we close this one?
